### PR TITLE
Fix SelectionRenderLayer._state

### LINKED ISSUE #1541: SelectionRenderLayer._state is broken
This doesn't work as it's comparing arrays. 

https://github.com/xtermjs/xterm.js/blob/1395b0f03cedcce7b8ece0da96ce92c8a66d4fe7/src/renderer/SelectionRenderLayer.ts#L41-L44

After https://github.com/xtermjs/xterm.js/pull/1538#issuecomment-401514599 is merged this should also include the selection mode.

### PR DESCRIPTION
**Pull request by nikonso**
Fixes #1541

### CODE REVIEW

File: src/renderer/SelectionRenderLayer.ts [hunk 1]
```diff
@@ -23,23 +24,27 @@ export class SelectionRenderLayer extends BaseRenderLayer {
...
+        columnSelectMode: null
       };
       this.clearAll();
     }
   }
 
   public onSelectionChanged(terminal: ITerminal, start: [number, number], end: [number, number], columnSelectMode: boolean): void {
     // Selection has not changed
-    if (this._state.start === start || this._state.end === end) {
+    if (this._areCoordinatesEqual(start, this._state.start) &&
```
Comment (Tyriar) [inline src/renderer/SelectionRenderLayer.ts]: Let's pull this into a `_didStateChange` helper function, other than that LGTM

**Comment by Tyriar** [comment]
Thanks as always :slightly_smiling_face:
