### PR TITLE
protection flag support

### LINKED ISSUE #3651: Full support for DECSED,DECSEL,DECSCA, etc for xtermjs
Using xtermjs in VSCode to an application which respects VT220 protection sequences. DECSED sequence erases the complete screen including the protected fields. This is incorrect behaviour and currently means our developers are unable to test within the IDE. 

Protected fields are normally protected from DESCSED erasure to support behaviour like clearing input data or updating areas without having to redraw the whole screen (maybe a throwback to 75 baud accousticly coupled modems?!).

Xtermjs InputHandler.ts currentlly says "Protection attributes are not supported". 

Issue #2358 was closed on the (false) premise these sequences are unused. Any chance these could be implemented?

### PR DESCRIPTION
**Pull request by jerch**
Fixes #3651.

TODO:
- [x] some unit tests
- [x] DECRQSS report
- [x] consolidate DECRQSS

@Tyriar Rewrote the PR, this time without additional work in `InputHandler.print`, so this should not impact normal print data flow at all. :muscle: 

Sidenote: Due to changing DECRQSS into an InputHandler function with some inline definitions I could save >3kB on the package.

Edit: Also fixed some feature docs, thus the website should be re-deployed at some point (still on v4.14).

### CODE REVIEW

File: src/common/InputHandler.ts [hunk 1]
```diff
@@ -1233,9 +1140,9 @@ export class InputHandler extends Disposable implements IInputHandler {
    * The cell gets replaced with the eraseChar of the terminal and the isWrapped property is set to false.
    * @param y row index
    */
-  private _resetBufferLine(y: number): void {
+  private _resetBufferLine(y: number, protect: boolean = false): void {
     const line = this._activeBuffer.lines.get(this._activeBuffer.ybase + y)!;
-    line.fill(this._activeBuffer.getNullCell(this._eraseAttrData()));
+    line.fill(this._activeBuffer.getNullCell(this._eraseAttrData()), protect);
```
Comment (Tyriar) [inline src/common/InputHandler.ts:1145]: I was a little confused reading the PR initially because it seemed like `protect` here was a cell's protection attribute being applied to the entire line. Would these be better as `respectProtect`? Also `@param` docs here would help

**Review by Tyriar — CHANGES_REQUESTED** [review]
Haven't tested but looks good other than my clean up comment

File: src/common/InputHandler.ts (hunk 1 above)
Comment (jerch) [reply src/common/InputHandler.ts]: Changed.

**Review by Tyriar — APPROVED** [review]
