### PR TITLE
fix double underline, upwards

### LINKED ISSUE #4476: canvas renderer and curly
Not sure if this is linked to the other canvas underline issues, but the curly underline does not look very curly to me:

image

(Get the same output in Chrome && Firefox...)

### PR DESCRIPTION
**Pull request by tisilent**
fix #4476

### CODE REVIEW

File: src/browser/renderer/shared/TextureAtlas.ts [hunk 1]
```diff
@@ -1019,13 +1020,13 @@ function clearColor(imageData: ImageData, bg: IColor, fg: IColor, enableThreshol
...
-        imageData.data[offset + 2] === b) {
+      imageData.data[offset + 1] === g &&
+      imageData.data[offset + 2] === b) {
       imageData.data[offset + 3] = 0;
     } else {
       // Check the threshold based difference
       if (enableThresholdCheck &&
-          (Math.abs(imageData.data[offset] - r) +
+        (Math.abs(imageData.data[offset] - r) +
           Math.abs(imageData.data[offset + 1] - g) +
```
Comment (Tyriar) [inline src/browser/renderer/shared/TextureAtlas.ts:1030]: Can you revert these? The intent here is to double-indent wrapped lines to easily differentiate them from the lines inside the block. You might need to disable prettier if you're using that.

File: src/browser/renderer/shared/TextureAtlas.ts [hunk 2]
```diff
@@ -542,10 +543,10 @@ export class TextureAtlas implements ITextureAtlas {
         const xChMid = xChLeft + this._config.deviceCellWidth / 2;
         switch (this._workAttributeData.extended.underlineStyle) {
           case UnderlineStyle.DOUBLE:
+            this._tmpCtx.moveTo(xChLeft, yTop - ySpace);
+            this._tmpCtx.lineTo(xChRight, yTop - ySpace);
             this._tmpCtx.moveTo(xChLeft, yTop);
             this._tmpCtx.lineTo(xChRight, yTop);
```
Comment (Tyriar) [inline src/browser/renderer/shared/TextureAtlas.ts:549]: Since we're fixing a limitation of the canvas renderer, we still want the old ideal behavior on the webgl renderer. So this should be based on a flag passed into `_drawToCache`, something like `restrictToCellHeight: boolean`

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/browser/renderer/shared/TextureAtlas.ts (hunk 1 above)
Comment (tisilent) [reply src/browser/renderer/shared/TextureAtlas.ts:1030]: ou.....I restore it. 😶‍🌫️

**Review by Tyriar — APPROVED** [review]
Works great 👍 

I created https://github.com/xtermjs/xterm.js/issues/4653 as we want a similar fix to curly too, ideally we would have a generic solution for this problem that ensures all underlines are within the cell for that.
