### PR TITLE
Fix canvas underline is cut off.

### LINKED ISSUE #4653: canvas renderer curly underline is cut off
This is tracking https://github.com/xtermjs/xterm.js/issues/4476 but for curly, where curly is dashed on canvas as it's cut off.

Related: https://github.com/xtermjs/xterm.js/issues/4064

### PR DESCRIPTION
**Pull request by tisilent**
fix #4653

### CODE REVIEW

File: src/browser/renderer/shared/TextureAtlas.ts [hunk 1]
```diff
@@ -532,10 +532,11 @@ export class TextureAtlas implements ITextureAtlas {
...
       const xLeft = padding;
-      const yTop = Math.ceil(padding + this._config.deviceCharHeight) - yOffset;
-      const yMid = padding + this._config.deviceCharHeight + lineWidth - yOffset;
-      const yBot = Math.ceil(padding + this._config.deviceCharHeight + lineWidth * 2) - yOffset;
-      const ySpace = lineWidth * 2;
+      const yTop = restrictToCellHeight ?
+        Math.ceil(padding + this._config.deviceCharHeight) - yOffset - lineWidth * 2 :
+        Math.ceil(padding + this._config.deviceCharHeight) - yOffset;
+      const yMid = yTop + lineWidth;
+      const yBot = yTop + lineWidth * 2;
```
Comment (Tyriar) [inline src/browser/renderer/shared/TextureAtlas.ts:539]: Nice, just the sort of thing I was thinking!

I'll keep a look out for any regressions as we are handling decimal values slightly differently, it seems to work after a quick test though and the change should only be with `yMid` which is for curly

**Review by Tyriar — APPROVED** [review]

File: src/browser/renderer/shared/TextureAtlas.ts [hunk 2]
```diff
@@ -532,10 +532,11 @@ export class TextureAtlas implements ITextureAtlas {
       // Underline style/stroke
       this._tmpCtx.beginPath();
       const xLeft = padding;
-      const yTop = Math.ceil(padding + this._config.deviceCharHeight) - yOffset;
-      const yMid = padding + this._config.deviceCharHeight + lineWidth - yOffset;
-      const yBot = Math.ceil(padding + this._config.deviceCharHeight + lineWidth * 2) - yOffset;
-      const ySpace = lineWidth * 2;
+      const yTop = restrictToCellHeight ?
+        Math.ceil(padding + this._config.deviceCharHeight) - yOffset - lineWidth * 2 :
+        Math.ceil(padding + this._config.deviceCharHeight) - yOffset;
```
Comment (Tyriar) [inline src/browser/renderer/shared/TextureAtlas.ts:537]:
```suggestion
      const yTop = Math.ceil(padding + this._config.deviceCharHeight) - yOffset - (restrictToCellHeight ? lineWidth * 2 : 0);
```
