### PR TITLE
Use proper height and fix alignment for positioned overview ruler decorations

### LINKED ISSUE #3683: Alignment for overview ruler decorations on the same line is off
The alignment seems off with these:

image

Also blue/right is being drawn largest?

_Originally posted by @Tyriar in https://github.com/xtermjs/xterm.js/pull/3676#discussion_r827513493_

### PR DESCRIPTION
**Pull request by meganrogge**
fixes #3683
when width is `15px`
Screen Shot 2022-03-16 at 1 22 20 PM
when width is `14px`
Screen Shot 2022-03-16 at 1 22 47 PM

### CODE REVIEW

File: src/browser/Decorations/OverviewRulerRenderer.ts [hunk 1]
```diff
@@ -91,13 +91,14 @@ export class OverviewRulerRenderer extends Disposable {
...
     this._ctx.strokeStyle = decoration.options.overviewRulerOptions.color;
-    this._ctx.strokeRect(
+    this._ctx.fillStyle = decoration.options.overviewRulerOptions.color;
+    this._ctx.fillRect(
       !decoration.options.overviewRulerOptions.position ||  decoration.options.overviewRulerOptions.position === 'left' ? 0 : decoration.options.overviewRulerOptions.position === 'right' ? renderSizes[SizeIndex.OUTER_SIZE] + renderSizes[SizeIndex.INNER_SIZE]: renderSizes[SizeIndex.OUTER_SIZE],
       Math.round(this._canvas.height * (decoration.options.marker.line / this._bufferService.buffers.active.lines.length)),
-      !decoration.options.overviewRulerOptions.position ? this._width : decoration.options.overviewRulerOptions.position === 'center' ? renderSizes[SizeIndex.INNER_SIZE]: renderSizes[SizeIndex.OUTER_SIZE],
-      window.devicePixelRatio
+      !decoration.options.overviewRulerOptions.position ? this._width : decoration.options.overviewRulerOptions.position === 'center' ? renderSizes[SizeIndex.INNER_SIZE] : renderSizes[SizeIndex.OUTER_SIZE],
+      window.devicePixelRatio * (!decoration.options.overviewRulerOptions.position ? 2 : 6)
```
Comment (Tyriar) [inline src/browser/Decorations/OverviewRulerRenderer.ts:101]: This is a bit hard to understand

**Review by Tyriar — APPROVED** [review]

File: src/browser/Decorations/OverviewRulerRenderer.ts (hunk 1 above)
Comment (meganrogge) [reply src/browser/Decorations/OverviewRulerRenderer.ts:101]: adding a comment
