### PR TITLE
trycatch characterJoiner handlers

### LINKED ISSUE #3547: A crashing character joiner brings down the whole terminal
In particular, `opentype.js` cannot parse the updated Monaco font file in macOS Monterey (`No valid cmap sub-tables found.`), rendering xterm unusable when the ligature addon is active.

### PR DESCRIPTION
**Pull request by LabhanshAgrawal**
Fixes #3547

### CODE REVIEW

File: src/browser/services/CharacterJoinerService.ts [hunk 1]
```diff
@@ -176,10 +176,20 @@ export class CharacterJoinerService implements ICharacterJoinerService {
     // At this point we already know that there is at least one joiner so
     // we can just pull its value and assign it directly rather than
     // merging it into an empty array, which incurs unnecessary writes.
-    const joinedRanges: [number, number][] = this._characterJoiners[0].handler(text);
+    let joinedRanges: [number, number][] = [];
```
Comment (Tyriar) [inline src/browser/services/CharacterJoinerService.ts:179]: This should go back to `const` since it's assigned only once. I was confused reviewing this due to the similarly of `joinerRanges` and `joinedRanges`, how about we rename `joinedRanges` -> `allJoinedRanges` to clarify?

File: src/browser/services/CharacterJoinerService.ts [hunk 2]
```diff
@@ -176,10 +176,20 @@ export class CharacterJoinerService implements ICharacterJoinerService {
...
+    try {
+      joinedRanges = this._characterJoiners[0].handler(text);
+    } catch (error) {
+      console.error(error);
+    }
     for (let i = 1; i < this._characterJoiners.length; i++) {
       // We merge any overlapping ranges across the different joiners
-      const joinerRanges = this._characterJoiners[i].handler(text);
+      let joinerRanges: [number, number][] = [];
```
Comment (Tyriar) [inline src/browser/services/CharacterJoinerService.ts:187]: This should go back to `const` since it's assigned only once.

File: src/browser/services/CharacterJoinerService.ts [hunk 3]
```diff
@@ -176,10 +176,20 @@ export class CharacterJoinerService implements ICharacterJoinerService {
...
+      try {
+        joinerRanges = this._characterJoiners[i].handler(text);
+      } catch (error) {
+        console.error(error);
```
Comment (Tyriar) [inline src/browser/services/CharacterJoinerService.ts:191]: If this one fails we'll need to skip the for loop as well, let's move that into the `try` block

**Review by Tyriar — CHANGES_REQUESTED** [review]

File: src/browser/services/CharacterJoinerService.ts (hunk 1 above)
Comment (LabhanshAgrawal) [reply src/browser/services/CharacterJoinerService.ts:179]: Since we have to try catch the first handler call as well, we'll need to instantiate this with empty array first.
If we want to keep it as `const` then, should I push the results from first handler? In that case, it'd be better to just have the loop start from index 0

File: src/browser/services/CharacterJoinerService.ts (hunk 3 above)
Comment (LabhanshAgrawal) [reply src/browser/services/CharacterJoinerService.ts:191]: sure

File: src/browser/services/CharacterJoinerService.ts (hunk 2 above)
Comment (LabhanshAgrawal) [reply src/browser/services/CharacterJoinerService.ts:187]: sure

File: src/browser/services/CharacterJoinerService.ts (hunk 1 above)
Comment (Tyriar) [reply src/browser/services/CharacterJoinerService.ts:179]: Makes sense as is 👌, we should do the rename though

**Review by Tyriar — APPROVED** [review]
Thanks @LabhanshAgrawal 👍

**Comment by LabhanshAgrawal** [comment]
Can we get a patch release, please 🙏
4.16 is nearly 2 weeks later.

**Comment by Tyriar** [comment]
@LabhanshAgrawal any reason you don't just pick up the beta? I only really have time to release during our "debt week" which is in 2 weeks

**Comment by LabhanshAgrawal** [comment]
Oh, didn't think about that. Will test with that and see. Thanks.
