### PR TITLE
Fix various problems with reflow

### LINKED ISSUE #1910: Terminal can crash when reflowing with a lot of wide characters in the prompt/cursor line
It appears to be related to Buffer.y becoming < 0 and also Buffer.ybase becoming too large.

```
TypeError: Cannot read property 'set' of undefined
    at InputHandler.print (InputHandler.ts:434)
    at EscapeSequenceParser._printHandler (InputHandler.ts:128)
    at EscapeSequenceParser.parse (EscapeSequenceParser.ts:442)
    at InputHandler.parse (InputHandler.ts:299)
    at Terminal._innerWrite (Terminal.ts:1372)
    at Terminal.ts:1341
```

```
ERR Cannot read property '_data' of undefined: TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Buffer.js:244:45)
    at Buffer._reflow (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Buffer.js:170:18)
    at Buffer.resize (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/Terminal.js:1096:22)
    at Terminal.resize (/Users/daimms/dev/Microsoft/vscode/node_modules/vscode-xterm/lib/public/Terminal.js:53:20)
```

### PR DESCRIPTION
**Pull request by Tyriar**
- No longer reflow lines where the full unwrapped line contains the cursor
- Add guards to prevent y and ybase becoming invalid values

Part of Microsoft/vscode#67364
Fixes #1910

### CODE REVIEW

File: src/Buffer.ts [hunk 1]
```diff
@@ -285,6 +289,13 @@ export class Buffer implements IBuffer {
         wrappedLines.unshift(nextLine);
       }
 
+      // If these lines contain the cursor don't touch them, the program will handle fixing up
+      // wrapped lines with the cursor
+      const absoluteY = this.ybase + this.y;
+      if (absoluteY >= y && absoluteY < y + wrappedLines.length) {
```
Comment (jerch) [inline src/Buffer.ts]: What happens here, if the cursor is not in the last row (e.g. after the cursor jumped some lines backwards)? I guess `absoluteY >= y` will turn true for any line after the cursor?

File: src/Buffer.ts [hunk 2]
```diff
@@ -357,10 +368,13 @@ export class Buffer implements IBuffer {
             this.ydisp++;
           }
         } else {
-          if (this.ybase === this.ydisp) {
-            this.ydisp++;
+          // Ensure ybase does not exceed its maximum value
```
Comment (jerch) [inline src/Buffer.ts]: Did you spot overflows here? I mean you do quite some calculations at the beginning to skip line content at the scroll buffer top that would be cut off anyway. Maybe there is an offset error that gets carried on?

Comment (Tyriar) [reply src/Buffer.ts]: There might be a calculation off somewhere, but this and the `this.y` check seemed to fix the majority of the issues. We also want these just in case as invalid values can brick the terminal and make it unusable.
