### PR TITLE
fixed ScreenDprListener never being fired

### LINKED ISSUE #2137: Display density changes lead to corrupted characters
When switching between a built-in Retina display and an external normal-density display, some characters will be drawn with incorrect size by the canvas renderer.

Now, I can't confirm whether it's possibly Electron's fault, but I suspect that Chrome would behave the same.

xterm 3.13.2

image

### PR DESCRIPTION
**Pull request by Eugeny**
Fixes #2137

### CODE REVIEW

File: src/browser/ScreenDprMonitor.ts [hunk 1]
```diff
@@ -44,12 +44,14 @@ export class ScreenDprMonitor extends Disposable {
...
-    if (!this._resolutionMediaMatchList || !this._outerListener) {
+    if (!this._outerListener) {
       return;
     }
 
     // Clear listeners for old DPR
-    this._resolutionMediaMatchList.removeListener(this._outerListener);
+    if (this._resolutionMediaMatchList) {
+      this._resolutionMediaMatchList.removeListener(this._outerListener);
+    }
```
Comment (Tyriar) [inline src/browser/ScreenDprMonitor.ts:54]:
```suggestion
    this._resolutionMediaMatchList?.removeListener(this._outerListener);
```

**Comment by Eugeny** [comment]
Added the change.

**Comment by Tyriar** [comment]
👍 thanks!
